# Generated by Django 6.0 on 2025-12-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
